export const LEFT_SIDE_AREA = 'LEFT_SIDE_AREA';
export const RIGHT_SIDE_AREA = 'RIGHT_SIDE_AREA';

export const PROFILE_MAIN_AREA = 'PROFILE_MAIN_AREA';
export const ABOUT_ME_AREA = 'ABOUT_ME_AREA';
export const REWARDS_STORE_AREA = 'REWARDS_STORE_AREA';
export const POINTS_HISTORY_AREA = 'POINTS_HISTORY_AREA';

export const CHAT_MAIN_AREA = 'CHAT_MAIN_AREA';
export const CHAT_AREA = 'CHAT_AREA';

export const COMMUNITIES_MAIN_AREA = 'COMMUNITIES_MAIN_AREA';
export const CLASSES_AREA = 'CLASSES_AREA';
export const BOOKMARKED_POSTS_AREA = 'BOOKMARKED_POSTS_AREA';
export const CLASSMATES_AREA = 'CLASSMATES_AREA';
export const FEEDS_AREA = 'FEEDS_AREA';

export const STUDY_TOOLS_MAIN_AREA = 'STUDY_TOOLS_MAIN_AREA';
export const NOTES_AREA = 'NOTES_AREA';
export const FLASHCARDS_AREA = 'FLASHCARDS_AREA';
export const CALENDAR_AREA = 'CALENDAR_AREA';
export const STUDY_TIPS_AREA = 'STUDY_TIPS_AREA';

export const ACHIEVEMENTS_MAIN_AREA = 'ACHIEVEMENTS_MAIN_AREA';
export const GOALS_AREA = 'GOALS_AREA';
export const BADGES_AREA = 'BADGES_AREA';
export const LEADERBOARD_AREA = 'LEADERBOARD_AREA';
export const SCHOLARSHIPS_AREA = 'SCHOLARSHIPS_AREA';

export const MORE_MAIN_AREA = 'MORE_MAIN_AREA';
export const SUPPORT_AREA = 'SUPPORT_AREA';
export const GIVE_FEEDBACK_AREA = 'GIVE_FEEDBACK_AREA';
export const GET_THE_MOBILE_APP_AREA = 'GET_THE_MOBILE_APP_AREA';
export const UNBLOCK_CLASSMATES_AREA = 'UNBLOCK_CLASSMATES_AREA';
export const STUDENT_HELP_AREA = 'STUDENT_HELP_AREA';

export const mainAreasInOrder: string[] = [
  PROFILE_MAIN_AREA,
  CHAT_MAIN_AREA,
  COMMUNITIES_MAIN_AREA,
  STUDY_TOOLS_MAIN_AREA,
  ACHIEVEMENTS_MAIN_AREA,
  MORE_MAIN_AREA
];

export const mainSubAreasInOrder: Record<string, string[]> = {
  [PROFILE_MAIN_AREA]: [ABOUT_ME_AREA, POINTS_HISTORY_AREA, REWARDS_STORE_AREA],
  [CHAT_MAIN_AREA]: [CHAT_AREA],
  [COMMUNITIES_MAIN_AREA]: [CLASSES_AREA, FEEDS_AREA],
  [STUDY_TOOLS_MAIN_AREA]: [FLASHCARDS_AREA, NOTES_AREA, CALENDAR_AREA, STUDY_TIPS_AREA],
  [ACHIEVEMENTS_MAIN_AREA]: [LEADERBOARD_AREA],
  [MORE_MAIN_AREA]: [SUPPORT_AREA, GIVE_FEEDBACK_AREA, GET_THE_MOBILE_APP_AREA]
};
