export const BOTTOM_LEFT_SIDE_AREA = 'BOTTOM_LEFT_SIDE_AREA';
export const TOP_LEFT_SIDE_AREA = 'TOP_LEFT_SIDE_AREA';
export const BOTTOM_RIGHT_SIDE_AREA = 'BOTTOM_RIGHT_SIDE_AREA';
export const TOP_RIGHT_SIDE_AREA = 'TOP_RIGHT_SIDE_AREA';

export const PROFILE_MAIN_AREA = 'PROFILE_MAIN_AREA';
export const ABOUT_ME_AREA = 'ABOUT_ME_AREA';
export const POINTS_HISTORY_AREA = 'POINTS_HISTORY_AREA';
export const REWARDS_STORE_AREA = 'REWARDS_STORE_AREA';

export const COMMUNITIES_MAIN_AREA = 'COMMUNITIES_MAIN_AREA';
export const CLASSES_AREA = 'CLASSES_AREA';
export const FEEDS_AREA = 'FEEDS_AREA';

export const STUDY_TOOLS_MAIN_AREA = 'STUDY_TOOLS_MAIN_AREA';
export const NOTES_AREA = 'NOTES_AREA';
export const FLASHCARDS_AREA = 'FLASHCARDS_AREA';
export const CALENDAR_AREA = 'CALENDAR_AREA';
export const STUDY_TIPS_AREA = 'STUDY_TIPS_AREA';

export const ACHIEVEMENTS_MAIN_AREA = 'ACHIEVEMENTS_MAIN_AREA';
export const GOALS_AREA = 'GOALS_AREA';
export const BADGES_AREA = 'BADGES_AREA';
export const LEADERBOARD_AREA = 'LEADERBOARD_AREA';
export const SCHOLARSHIPS_AREA = 'SCHOLARSHIPS_AREA';

export const MORE_MAIN_AREA = 'MORE_MAIN_AREA';
export const SUPPORT_AREA = 'SUPPORT_AREA';
export const GIVE_FEEDBACK_AREA = 'GIVE_FEEDBACK_AREA';
export const GET_THE_MOBILE_APP_AREA = 'GET_THE_MOBILE_APP_AREA';

export const mainAreasInOrder: string[] = [
  PROFILE_MAIN_AREA,
  COMMUNITIES_MAIN_AREA,
  STUDY_TOOLS_MAIN_AREA,
  ACHIEVEMENTS_MAIN_AREA,
  MORE_MAIN_AREA
];

export const mainSubAreasInOrder: Record<string, string[]> = {
  [PROFILE_MAIN_AREA]: [ABOUT_ME_AREA, POINTS_HISTORY_AREA, REWARDS_STORE_AREA],
  [COMMUNITIES_MAIN_AREA]: [CLASSES_AREA, FEEDS_AREA],
  [STUDY_TOOLS_MAIN_AREA]: [NOTES_AREA, FLASHCARDS_AREA, CALENDAR_AREA, STUDY_TIPS_AREA],
  [ACHIEVEMENTS_MAIN_AREA]: [GOALS_AREA, BADGES_AREA, LEADERBOARD_AREA, SCHOLARSHIPS_AREA],
  [MORE_MAIN_AREA]: [SUPPORT_AREA, GIVE_FEEDBACK_AREA, GET_THE_MOBILE_APP_AREA]
};

export const areaToDisplayName: Record<string, string> = {
  [BOTTOM_LEFT_SIDE_AREA]: 'Chat Channels',
  [TOP_LEFT_SIDE_AREA]: 'Chat Messages',
  [BOTTOM_RIGHT_SIDE_AREA]: 'Next Missions',
  [TOP_RIGHT_SIDE_AREA]: 'Current Missions',

  [PROFILE_MAIN_AREA]: 'Profile',
  [ABOUT_ME_AREA]: 'About Me',
  [POINTS_HISTORY_AREA]: 'Points History',
  [REWARDS_STORE_AREA]: 'Rewards Store',

  [COMMUNITIES_MAIN_AREA]: 'Communities',
  [CLASSES_AREA]: 'Classes',
  [FEEDS_AREA]: 'Class Feeds',

  [STUDY_TOOLS_MAIN_AREA]: 'Study Tools',
  [NOTES_AREA]: 'Notes',
  [FLASHCARDS_AREA]: 'Flashcards',
  [CALENDAR_AREA]: 'Calendar',
  [STUDY_TIPS_AREA]: 'Study Tips',

  [ACHIEVEMENTS_MAIN_AREA]: 'Achievements',
  [GOALS_AREA]: 'Goals',
  [BADGES_AREA]: 'Badges',
  [LEADERBOARD_AREA]: 'Leaderboard',
  [SCHOLARSHIPS_AREA]: 'Scholarships',

  [MORE_MAIN_AREA]: 'More...',
  [SUPPORT_AREA]: 'Support',
  [GIVE_FEEDBACK_AREA]: 'Give Feedback',
  [GET_THE_MOBILE_APP_AREA]: 'Get the Mobile App'
};
