export const LEFT_SIDE_AREA = 'LEFT_SIDE_AREA';
export const RIGHT_SIDE_AREA = 'RIGHT_SIDE_AREA';

export const NOTIFICATIONS_AREA = 'NOTIFICATIONS_AREA';
export const PROFILE_MAIN_AREA = 'PROFILE_MAIN_AREA';
export const ABOUT_ME_AREA = 'ABOUT_ME_AREA';
export const REWARDS_STORE_AREA = 'REWARDS_STORE_AREA';
export const POINTS_HISTORY_AREA = 'POINTS_HISTORY_AREA';
export const SIGN_OUT_BUTTON = 'SIGN_OUT_BUTTON';

export const CHAT_MAIN_AREA = 'CHAT_MAIN_AREA';
export const CHAT_AREA = 'CHAT_AREA';

export const COMMUNITIES_MAIN_AREA = 'COMMUNITIES_MAIN_AREA';
export const CLASSES_AREA = 'CLASSES_AREA';
export const FEEDS_AREA = 'FEEDS_AREA';
export const CREATE_A_POST_AREA = 'CREATE_A_POST_AREA';
export const ASK_A_QUESTION_AREA = 'ASK_A_QUESTION_AREA';
export const SHARE_NOTES_AREA = 'SHARE_NOTES_AREA';
export const SHARE_RESOURCES_AREA = 'SHARE_RESOURCES_AREA';

export const STUDY_TOOLS_MAIN_AREA = 'STUDY_TOOLS_MAIN_AREA';
export const NOTES_AREA = 'NOTES_AREA';
export const FLASHCARDS_AREA = 'FLASHCARDS_AREA';
export const CALENDAR_AREA = 'CALENDAR_AREA';
export const STUDY_TIPS_AREA = 'STUDY_TIPS_AREA';

export const ACHIEVEMENTS_MAIN_AREA = 'ACHIEVEMENTS_MAIN_AREA';
export const GOALS_AREA = 'GOALS_AREA';
export const BADGES_AREA = 'BADGES_AREA';
export const LEADERBOARD_AREA = 'LEADERBOARD_AREA';
export const SCHOLARSHIPS_AREA = 'SCHOLARSHIPS_AREA';

export const MORE_MAIN_AREA = 'MORE_MAIN_AREA';
export const SUPPORT_AREA = 'SUPPORT_AREA';
export const GIVE_FEEDBACK_AREA = 'GIVE_FEEDBACK_AREA';
export const GET_THE_MOBILE_APP_AREA = 'GET_THE_MOBILE_APP_AREA';
export const UNBLOCK_CLASSMATES_AREA = 'UNBLOCK_CLASSMATES_AREA';
export const STUDENT_HELP_AREA = 'STUDENT_HELP_AREA';
