export const hudEventNames = {
  CURRENT_STORY_COMPLETED: 'CURRENT_STORY_COMPLETED',

  START_ONBOARDING: 'START_ONBOARDING',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',

  SHOW_NAVIGATION_TO_LEADERBOARD: 'SHOW_NAVIGATION_TO_LEADERBOARD',
  SHOW_NAVIGATION_TO_REWARDS_STORE: 'SHOW_NAVIGATION_TO_REWARDS_STORE',
  SHOW_NAVIGATION_TO_FLASHCARDS: 'SHOW_NAVIGATION_TO_FLASHCARDS',
  SHOW_NAVIGATION_TO_WORKFLOW: 'SHOW_NAVIGATION_TO_WORKFLOW',

  REWARDS_SELECTIONS_EMPTY: 'REWARDS_SELECTIONS_EMPTY',
  REWARDS_SELECTIONS_PARTIALLY_FILLED: 'REWARDS_SELECTIONS_PARTIALLY_FILLED',
  REWARDS_SELECTIONS_FILLED: 'REWARDS_SELECTIONS_FILLED',

  NAVIGATED_TO_AREA: 'NAVIGATED_TO_AREA'
};
