export const hudEventNames = {
  CURRENT_STORY_COMPLETED: 'CURRENT_STORY_COMPLETED',

  START_ONBOARDING: 'START_ONBOARDING',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',

  SHOW_INTRO_TO_CLASS_FEED: 'SHOW_INTRO_TO_CLASS_FEED',
  INTRO_TO_STUDY_TOOLS: 'INTRO_TO_STUDY_TOOLS',
  SHOW_NAVIGATION_TO_LEADERBOARD: 'SHOW_NAVIGATION_TO_LEADERBOARD',
  SHOW_NAVIGATION_TO_REWARDS_STORE: 'SHOW_NAVIGATION_TO_REWARDS_STORE',
  SHOW_NAVIGATION_TO_CLASS_FEED: 'SHOW_NAVIGATION_TO_CLASS_FEED',
  SHOW_NAVIGATION_TO_CHAT: 'SHOW_NAVIGATION_TO_CHAT',

  REWARDS_SELECTIONS_EMPTY_OR_PARTIALLY_FILLED: 'REWARDS_SELECTIONS_EMPTY_OR_PARTIALLY_FILLED',
  REWARDS_SELECTIONS_FILLED: 'REWARDS_SELECTIONS_FILLED',

  NAVIGATED_TO_AREA: 'NAVIGATED_TO_AREA'
};
