// flow-typed signature: 76999cc42d76704dff6f555abf290718
// flow-typed version: <<STUB>>/react-material-ui-form-validator_v^2.0.3/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-material-ui-form-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-material-ui-form-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-material-ui-form-validator/lib/index' {
  declare module.exports: any;
}

declare module 'react-material-ui-form-validator/lib/SelectValidator' {
  declare module.exports: any;
}

declare module 'react-material-ui-form-validator/lib/TextValidator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-material-ui-form-validator/lib/index.js' {
  declare module.exports: $Exports<'react-material-ui-form-validator/lib/index'>;
}
declare module 'react-material-ui-form-validator/lib/SelectValidator.js' {
  declare module.exports: $Exports<'react-material-ui-form-validator/lib/SelectValidator'>;
}
declare module 'react-material-ui-form-validator/lib/TextValidator.js' {
  declare module.exports: $Exports<'react-material-ui-form-validator/lib/TextValidator'>;
}
