// flow-typed signature: 310fe72126df5fb10659fe0dfc0fbd99
// flow-typed version: <<STUB>>/@microlink/react_v^3.0.5/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@microlink/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@microlink/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@microlink/react/lib/components/Card/CardAnimation' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardContent' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardEmpty' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardMedia/Image' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardMedia/index' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardMedia/loader' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardMedia/Video/controls' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardMedia/Video/index' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardMedia/wrap' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardText' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/CardWrap' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/components/Card/index' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/index' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/index.m' {
  declare module.exports: any;
}

declare module '@microlink/react/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@microlink/react/lib/components/Card/CardAnimation.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardAnimation'>;
}
declare module '@microlink/react/lib/components/Card/CardContent.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardContent'>;
}
declare module '@microlink/react/lib/components/Card/CardEmpty.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardEmpty'>;
}
declare module '@microlink/react/lib/components/Card/CardMedia/Image.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardMedia/Image'>;
}
declare module '@microlink/react/lib/components/Card/CardMedia/index.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardMedia/index'>;
}
declare module '@microlink/react/lib/components/Card/CardMedia/loader.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardMedia/loader'>;
}
declare module '@microlink/react/lib/components/Card/CardMedia/Video/controls.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardMedia/Video/controls'>;
}
declare module '@microlink/react/lib/components/Card/CardMedia/Video/index.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardMedia/Video/index'>;
}
declare module '@microlink/react/lib/components/Card/CardMedia/wrap.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardMedia/wrap'>;
}
declare module '@microlink/react/lib/components/Card/CardText.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardText'>;
}
declare module '@microlink/react/lib/components/Card/CardWrap.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/CardWrap'>;
}
declare module '@microlink/react/lib/components/Card/index.js' {
  declare module.exports: $Exports<'@microlink/react/lib/components/Card/index'>;
}
declare module '@microlink/react/lib/index.js' {
  declare module.exports: $Exports<'@microlink/react/lib/index'>;
}
declare module '@microlink/react/lib/index.m.js' {
  declare module.exports: $Exports<'@microlink/react/lib/index.m'>;
}
declare module '@microlink/react/lib/utils/index.js' {
  declare module.exports: $Exports<'@microlink/react/lib/utils/index'>;
}
